### PR TITLE
Fix link for GitHub repo and homepage

### PR DESCRIPTION
**Pull request by vishal-sood**
Fix the typo in links in the following fields in `package.json`:
- `repository.url`
- `bugs.url`
- `homepage`

### CODE REVIEW

**Comment by rohit-gohri** [comment]
Also, I think I accidentally published this from my npm account (rohit-smpx). Can transfer if requested.

**Comment by hit12369** [comment]
> Also, I think I accidentally published this from my npm account (rohit-smpx). Can transfer if requested.

That would be good.

**Comment by rohit-gohri** [comment]
@hit12369 Sent you a maintainer invite (`smartprix` user). You can transfer it to org later : https://docs.npmjs.com/managing-team-access-to-org-packages#adding-package-access-to-a-team-on-the-web

**Comment by hit12369** [comment]
Awesome :+1:

**Pull request merged**
